version: '3'

services:
  textgen:
    image: saladtechnologies/text-generation-webui:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    build:
      context: .
      dockerfile: Dockerfile