version: '3'

services:
  textgen:
    image: saladtechnologies/text-generation-webui:91a7370
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: all
    ports:
      - "1879:80"
    build:
      context: .
      dockerfile: Dockerfile
